# A set of env vars to be set within the Edge Function environment
[env]
  # The DSN to use for the database connection. This will be set to the database for the project by default.
  # DATABASE_URL="postgresql://postgres:[YOUR-PASSWORD]@db.xxxxxxxxxxxxxxxxxxxx.supabase.co:5432/postgres"
  # The database URL to use for local migrations. This should be set to a local database.
  # LOCAL_DATABASE_URL="postgresql://postgres:postgres@localhost:5433/postgres"
  # The URL to use for the Supabase API. This will be set to the API for the project by default.
  # SUPABASE_URL="https://xxxxxxxxxxxxxxxxxxxx.supabase.co"
  # The anon key to use for the Supabase API. This will be set to the anon key for the project by default.
  # SUPABASE_ANON_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiaWF0IjoxNjQzNjM1OTY2LCJuYmYiOjE2NDM2MzU5NjYsImV4cCI6MTk1OTA5MTk2Niwi cm9sZSI6ImFub24ifQ.xxxxxxx"
  # The service role key to use for the Supabase API. This will be set to the service role key for the project by default.
  # SUPABASE_SERVICE_ROLE_KEY="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOiJhdXRoZW50aWNhdGVkIiwiaWF0IjoxNjQzNjM1OTY2LCJuYmYiOjE2NDM2MzU5NjYsImV4cCI6MTk1OTA5MTk2Niwi cm9sZSI6InNlcnZpY2Vfcm9sZSJ9.xxxxxxx"

# A list of database extensions to enable
[api]
  enabled = true
  cors = { enabled = true }

[db]
  enabled = true
  shadow_url = "${LOCAL_DATABASE_URL}"
  seeds = { enabled = false }
  migrations = { dir = "migrations" }

[functions]
  enabled = true
  serve_static_files = true

[storage]
  enabled = true
  file_size_limit = "5MiB"

[realtime]
  enabled = true
  ssl = true
  port = 4000
  tcp_port = 4000
  udp_port = 4000