# Règle de cache pour les assets immuables (JS, CSS, images, etc.)
# On leur donne une longue durée de vie en cache car leur nom change à chaque build.
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Règle spécifique pour le fichier HTML principal.
# On empêche sa mise en cache pour que les utilisateurs aient toujours la dernière version.
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"